name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Sync deps + editable install
        run: |
          uv venv .venv
          uv sync --extra dev
          uv pip install -e .
      - name: Lint
        run: uv run ruff check .
      - name: Format check
        run: uv run black --check .
      - name: Tests
        run: uv run python -m pytest -q
